name: test triggers

# manual only: doesn't work, must be on master branch or something
# on: workflow_dispatch

# on any push to specific branches:
#on:
#  push:
#    branches: [ "tunnelmode" ]
#  pull_request:
#    branches: [ "tunnelmode" ]

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test triggers
      run: echo "running......."
